const quotes = [
  "We are not rich by what we possess but by what we can do without.",
  "He who is cruel to animals becomes hard also in his dealings with men. We can judge the heart of a man by his treatment of animals.",
  "Act in such a way that you treat humanity, whether in your own person or in the person of any other, never merely as a means to an end, but always at the same time as an end.",
  "Enlightenment is man's release from his self-incurred tutelage. Tutelage is man's inability to make use of his understanding without direction from another. Self-incurred is this tutelage when its cause lies not in lack of reason but in lack of resolution and courage to use it without direction from another. Sapere aude! 'Have courage to use your own reason!'- that is the motto of enlightenment.",
  "Look closely. The beautiful may be small.",
  "Dare to think!",
  "One who makes himself a worm cannot complain afterwards if people step on him.",
  "I had to deny knowledge in order to make room for faith.",
  "Two things fill the mind with ever-increasing wonder and awe, the more often and the more intensely the mind of thought is drawn to them: the starry heavens above me and the moral law within me.",
  "All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason. There is nothing higher than reason.",
  "Two things fill the mind with ever new and increasing admiration and awe, the more often and steadily we reflect upon them: the starry heavens above me and the moral law within me. I do not seek or conjecture either of them as if they were veiled obscurities or extravagances beyond the horizon of my vision; I see them before me and connect them immediately with the consciousness of my existence.",
  "Whereas the beautiful is limited, the sublime is limitless, so that the mind in the presence of the sublime, attempting to imagine what it cannot, has pain in the failure but pleasure in contemplating the immensity of the attempt",
  "For peace to reign on Earth, humans must evolve into new beings who have learned to see the whole first.",
  "Out of the crooked timber of humanity, no straight thing was ever made.",
  "Seek not the favor of the multitude; it is seldom got by honest and lawful means. But seek the testimony of few; and number not voices, but weigh them.",
  "Rules for happiness: something to do, someone to love, something to hope for.",
  "The busier we are, the more acutely we feel that we live, the more conscious we are of life.",
  "Genius is the ability to independently arrive at and understand concepts that would normally have to be taught by another person.",
  "The death of dogma is the birth of morality.",
  "But only he who, himself enlightened, is not afraid of shadows.",
  "Space and time are the framework within which the mind is constrained to construct its experience of reality",
  "Thoughts without content are empty, intuitions without concepts are blind",
  "Science is organized knowledge. Wisdom is organized life.",
  "From such crooked wood as that which man is made of, nothing straight can be fashioned.",
  "By a lie, a man…annihilates his dignity as a man.",
  "It is not God’s will merely that we should be happy, but that we should make ourselves happy.",
  "A person is only a person when it has the power to make sense of its surrounding.",
  "So act that your principle of action might safely be made a law for the whole world.",
  "Morality is not the doctrine of how we may make ourselves happy, but how we may make ourselves worthy of happiness.",
  "Give me matter, and I will construct a world out of it!",
  "Notion without intuition is empty, intuition without notion is blind.",
  "Look closely. The beautiful may be small.",
  "Falling down is not a failure. Failure comes when you stay where you have fallen.",
  "When the debate is lost, slander becomes the tool of the loser.",
  "Awareness of ignorance is the beginning of wisdom.",
  "In every person there is a sun. Just let them shine.",
  "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.",
  "The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.",
  "He who is not contented with what he has, would not be contented with what he would like to have.",
  "Four things belong to a judge: to hear courteously, to answer wisely, to consider soberly, and to decide impartially.",
  "We are what we repeatedly do. Excellence then is a habit.",
  "He is the richest who is content with the least.",
  "I know that I am intelligent, because I know that I know nothing.",
  "It is better to suffer an injustice than to commit one",
  "I am a fool, but I know I'm a fool and that makes me smarter than you.",
  "Understanding a question is half an answer.",
  "To find yourself, think for yourself.",
  "Lies are the greatest murder. They kill the Truth.",
  "An education obtained with money is worse than no education at all.",
  "The soul, like the body, accepts by practice whatever habit one wishes it to contact."
]
module.exports = quotes